import { execFile } from 'child_process';
import path from 'path';
import fs from 'fs';
import os from 'os';

/**
 * LOGIC CHO IRONBREW2 CLI
 */

export interface ObfuscationConfig {
  vmEncryption: boolean;
  stringEncryption: boolean;
  controlFlowFlattening: boolean;
  memes: boolean;
}

// Hàm giả lập (Fallback)
function mockObfuscate(script: string, config: ObfuscationConfig): string {
  const header = "-- [ IronBrew Community Edition (Mock) ]\n-- Protected by NamelessGuard\n\n";
  let processed = script;

  if (config.stringEncryption) {
    processed = processed.replace(/'(.*?)'/g, "(function() return 'ENCRYPTED_STRING' end)()");
  }
  if (config.memes) {
    processed = `print("Protected by Nameless");\n${processed}`;
  }

  const vmStart = "local llIlIllIl = {}; -- Virtual Machine Start\n";
  const vmEnd = "\n-- Virtual Machine End";
  return `${header}${vmStart}${processed}${vmEnd}`;
}

export async function ironBrewObfuscate(script: string, config: ObfuscationConfig): Promise<string> {
  // 1. Xác định đường dẫn gốc của project
  const currentWorkingDir = (process as any).cwd();

  // 2. Trỏ vào thư mục bin: /api/obfuscation/bin/
  const binDir = path.join(currentWorkingDir, 'api', 'obfuscation', 'bin');

  // 3. Xác định tên file binary dựa trên hệ điều hành
  const isWin = (process as any).platform === 'win32';
  const binaryName = isWin ? 'IronBrew2.exe' : 'IronBrew2';
  
  const binaryPath = path.join(binDir, binaryName);
  
  // Debug log để bạn biết server đang tìm file ở đâu
  console.log(`[IronBrew] Looking for binary at: ${binaryPath}`);

  // Nếu file không tồn tại, dùng Mock
  if (!fs.existsSync(binaryPath)) {
    console.warn(`[IronBrew] Binary NOT FOUND. Using mock engine.`);
    return mockObfuscate(script, config);
  }

  // Tạo file tạm thời
  const tempDir = os.tmpdir();
  const uniqueId = `${Date.now()}_${Math.random().toString(36).substring(7)}`;
  const inputPath = path.join(tempDir, `ib_in_${uniqueId}.lua`);
  const outputPath = path.join(tempDir, `ib_out_${uniqueId}.lua`);

  try {
    // Ghi script gốc
    fs.writeFileSync(inputPath, script);

    // Config arguments (Sửa lại tùy theo version IronBrew CLI của bạn)
    // Ví dụ: IronBrew2.exe --input file.lua --output out.lua --vm --cff
    const args = [
      '--input', inputPath,
      '--output', outputPath
    ];

    if (config.vmEncryption) args.push('--vm');
    if (config.stringEncryption) args.push('--strings');
    if (config.controlFlowFlattening) args.push('--cff');

    console.log(`[IronBrew] Executing: ${binaryPath} ${args.join(' ')}`);

    // Gọi CLI
    await new Promise<void>((resolve, reject) => {
      execFile(binaryPath, args, {
        cwd: binDir, // Set thư mục làm việc là bin để nó load được libs/config
        timeout: 60000 // 60s timeout
      }, (error, stdout, stderr) => {
        if (error) {
          console.error("[IronBrew] Error Output:", stderr);
          reject(error);
        } else {
          resolve();
        }
      });
    });

    // Đọc kết quả
    if (fs.existsSync(outputPath)) {
      const result = fs.readFileSync(outputPath, 'utf-8');
      
      // Cleanup
      try {
        fs.unlinkSync(inputPath);
        fs.unlinkSync(outputPath);
      } catch (e) {}

      return result;
    } else {
      throw new Error("No output file generated by CLI.");
    }

  } catch (error: any) {
    console.error("[IronBrew] Execution Failed:", error);
    
    // Cleanup on error
    try {
      if (fs.existsSync(inputPath)) fs.unlinkSync(inputPath);
      if (fs.existsSync(outputPath)) fs.unlinkSync(outputPath);
    } catch (e) {}

    // Trả về Mock kèm thông báo lỗi để user biết
    return `-- [System Error] CLI Failed: ${error.message}\n` + mockObfuscate(script, config);
  }
}
